export const FETCH_QUIEZES_START = 'FETCH_QUIEZES_START'
export const FETCH_QUIEZES_SUCCESS = 'FETCH_QUIEZES_SUCCESS'
export const FETCH_QUIEZES_ERROR = 'FETCH_QUIEZES_ERROR'
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS'

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE'
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION'
export const QUIZ_RETRY = 'QUIZ_RETRY'
export const FINISH_QUIZ = 'FINISH_QUIZ'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'